# Copyright 2021-2022 FLECS Technologies GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG DISTRO
ARG SUITE

FROM ${DISTRO}:${SUITE}

ARG ARCH
ARG BUILD_DIR_BASE
ARG DISTRO
ARG SUITE
ARG DOCKER_VERSION
ARG DOCKER_RELEASE
ARG PRODUCT

RUN apt-get update

RUN apt-get -y --no-install-recommends install ca-certificates curl gnupg

COPY test/entrypoint.sh /

COPY test/install-depends.${PRODUCT}.sh /tmp/

RUN /tmp/install-depends.${PRODUCT}.sh

COPY ${BUILD_DIR_BASE}/flecs-${PRODUCT}_${DOCKER_VERSION}~${DOCKER_RELEASE}-0~${DISTRO}-${SUITE}_${ARCH}.deb /tmp/

RUN apt-get -y --no-install-recommends install /tmp/*.deb

ENTRYPOINT [ "/entrypoint.sh" ]
