name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]
        suite: ["buster", "bullseye"]
        include:
          - suite: buster
            distro: debian
          - suite: bullseye
            distro: debian

    steps:
      - uses: actions/checkout@v3
      - name: "Build and package"
        run: |
          make ARCH=${{ matrix.arch }} DISTRO=${{ matrix.distro }} SUITE=${{ matrix.suite }} all

      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*.deb
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    strategy:
      matrix:
        distro: ["debian"]
        suite: ["buster", "bullseye"]

    steps:
      - uses: actions/checkout@v3

      - name: Download workflow artifacts
        uses: actions/download-artifact@v3

      - name: "Test: amd64"
        run: |
          make ARCH=amd64 DISTRO=${{ matrix.distro }} SUITE=${{ matrix.suite }} test

  deploy:
    needs: test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        distro: ["debian"]
        suite: ["buster", "bullseye"]

    steps:
      - uses: actions/checkout@v3

      - name: Download workflow artifacts
        uses: actions/download-artifact@v3

      - name: Generate version file
        run: |
          make latest

      - name: Deploy packages
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "build/*${{ matrix.distro }}*${{ matrix.suite }}*.deb"
          target: ${{ secrets.MP_DOCKER_RELEASE_DIR }}/${{ matrix.distro }}/${{ matrix.suite }}
          strip_components: 1

      - name: Update latest file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "build/latest*"
          target: ${{ secrets.MP_DOCKER_RELEASE_DIR }}/${{ matrix.distro }}/${{ matrix.suite }}
          strip_components: 1
